### ISSUE TITLE
add new server

### ISSUE THREAD

**Issue by freehussain** [ICTO/BBB-Load-Balancer#20]
hello,

can you please give us how to add server example

**Comment by brunogoossens** [comment]
The easiest way to add a server is by using the web interface.

**Comment by freehussain** [comment]
hello,

Thanks for reply 

i use it but how?

https://domain.com/bigbluebutton ?

and where to enter secret?

**Comment by freehussain** [comment]
hello,

i found it finally 

only add like this 

https://domain.com 

:)

thank you for helping @brunogoossens

**Comment by brunogoossens** [comment]
![movie](https://user-images.githubusercontent.com/1636664/78153899-de518b80-743b-11ea-9c61-06f9c1650e24.gif)

**Comment by freehussain** [comment]
is there a way to add moodle bbb plugin you think? what is the url and secret
